---
title: "reddit_Notebook"
author: "Levi C. Nicklas"
date: "4/7/2021"
output: html_document
---

```{r setup, warning = FALSE, message=FALSE}
# Libraries
library(tidyverse)
library(here)
library(igraph)
library(graphkernels)
library(tidytext)
my_palette <-c("#ff333a","#f66025","#ffca3a","#8ac926","#1982c4","#6a4c93","#4b1592")

# Data Import
file.names <- list.files(path = here::here("Data/RawData"))

threads <- list()

for(i in 1:length(file.names)){
  temp.file.name <- here::here(paste0("Data/RawData/", file.names[i]))

  if(grepl("subreddit-",temp.file.name)){
    temp.file <- readRDS(temp.file.name)
    threads[[i]] <- temp.file
  }
}
```

Reformat the data to be text blobs _by thread_; observational unit in this analysis is now a **thread**.

```{r}
### Compress Thread text per post. ###

thread_text_list <- list()

for(j in 1:length(threads)){
  thread_df <- threads[[j]] 

  thread_df <- thread_df %>% 
  # Get top level of thread.
  mutate(thread_id = str_extract(structure,pattern = "[:digit:]{1,2}")) %>% 
  # Make Composite key of thread_ID and 
  mutate(post_thread_id = paste0(thread_id,"_x_",title)) 

  thread_df_compressed <- data.frame(post_thread_id = c(),
                                  text = c(),
                                  URL = c())
  post_threads <- unique(thread_df$post_thread_id)

  for(i in 1:length(post_threads)){
    thread_text <- thread_df %>% 
      filter(post_thread_id == post_threads[i]) %>% 
      select(comment) 
    thread_post <- thread_df %>% 
      filter(post_thread_id == post_threads[i]) %>% 
      select(post_text) %>% 
      unique() %>% 
      pull()
    thread_url <- thread_df %>% 
      filter(post_thread_id == post_threads[i]) %>% 
      select(URL) %>% 
      unique() %>% 
      pull()
    
    # Collapse Post and Comments into one blob.
    thread_text <- paste(thread_post, thread_text, collapse = ".")
    
    tmp_df <- data.frame(post_thread_id = c(post_threads[i]),
                                    text = c(thread_text),
                                    URL = c(thread_url))
    
    thread_df_compressed <- rbind(thread_df_compressed, tmp_df)
    #print(paste0("On Post ",j,", thread ",i))
  }
  thread_text_list[[j]] <- thread_df_compressed
  
}

rm(thread_df, temp.file, thread_df_compressed)
```


```{r}
# Make one big dataframe.

post_thread_text <- thread_text_list[[1]]
post_thread_text$queryword <- 1

for(i in 2:length(thread_text_list)){
  tmp_df <- thread_text_list[[i]]
  tmp_df$queryword <- i
  post_thread_text <- rbind(post_thread_text,tmp_df)
}

rm(threads, tmp_df)
```


## DATA CLEANING WITH EXISTING FUNCTIONS ##

Use `{furrr}` to make this computable in a reasonable amount of time.
```{r, warning = F, error = F, message = F}
source(here::here("Development/Scripts/df_to_graph_list.R"))
source(here::here("Development/Scripts/convert_to_graphs.R"))
#thread_graphs <- df_to_graph_list(post_thread_text$text)

# Will sample out 1000.
set.seed(23)
post_thread_text_sample <- sample_n(post_thread_text, 1000, replace = F)

thread_graphs <- convert_to_graphs()

#Takes a little bit, be patient.
```

## COMPUTE GRAPH KERNELS ##

```{r, message = F}
source(here::here("Development/Scripts/compute_graph_similarity.R"))
source(here::here("Development/Scripts/compute_kernel.R"))
#reddit_thread_kernel <- compute_kernel()

# This will take like 1 hr to run.
#saveRDS(reddit_thread_kernel, here::here("Data/ProcessedData/RedditThreadKerenel1000.RDS"))

reddit_thread_kernel <- readRDS(here::here("Data/ProcessedData/RedditThreadKerenel1000.RDS"))
```

Make one matrix

```{r}
reddit_thread_kernel_matrix <- matrix(data = rep(0, 1000*1000), nrow = 1000)

for(i in 1:length(reddit_thread_kernel)){
  reddit_thread_kernel_matrix[i,] <- reddit_thread_kernel[[i]]
}

rm(reddit_thread_kernel)
```

# Hierarchical Cluster

```{r}
# Any NA values?
thread_boolean <- reddit_thread_kernel_matrix[1,] %>% is.na() 

# Remove bad text threads -> NA's
post_thread_text_sample <- post_thread_text_sample[!thread_boolean,]

# Resize
reddit_thread_kernel_matrix <- reddit_thread_kernel_matrix[!thread_boolean,]
reddit_thread_kernel_matrix <- reddit_thread_kernel_matrix[,!thread_boolean]

#invert Matrix (Sim - > Dist)
reddit_thread_kernel_matrix <- 1/reddit_thread_kernel_matrix

library(caret)

pca_kernel <- reddit_thread_kernel_matrix %>% prcomp(scale. = T, center = T)

dendro_pca <- dist(pca_kernel$rotation, method = "manhattan") %>% 
  hclust(method = "ward.D")

dendro_pca %>% plot()

post_thread_text_sample$k2 <- dendro_pca %>% 
  cutree(k = 2)

post_thread_text_sample$k3 <- dendro_pca %>% 
  cutree(k = 3)

post_thread_text_sample$k4 <- dendro_pca %>% 
  cutree(k = 4)

post_thread_text_sample$k5 <- dendro_pca %>% 
  cutree(k = 5)

post_thread_text_sample$k6 <- dendro_pca %>% 
  cutree(k = 6)

post_thread_text_sample$k7 <- dendro_pca %>% 
  cutree(k = 7)

```

```{r, message=F}
library(factoextra)

reddit_dendo <- fviz_dend(dendro_pca, k = 3, cex = 0.5,  show_labels = F, k_colors = my_palette) +
  labs(x = "Document ID",
       y = "Height",
       title = "reddit Thread Documents - HClust",
       subtitle = "Manhattan Distance & Ward.D Linkage")

ggsave(reddit_dendo, filename = here::here("Thesis_Tex/Content/Images/reddit_dendo.png"))
```

```{r, include = F, eval = F}
fviz_pca_ind(pca_kernel, label="none", habillage = post_thread_text_sample$k3,
             addEllipses=F, ellipse.level=0.95)
```


```{r, include = F, eval = F}
fviz_pca_biplot(pca_kernel, label ="ind")
```

```{r}
post_thread_text_sample$x <- pca_kernel$x[,1]
post_thread_text_sample$y <- pca_kernel$x[,2]

#K2
# Compute Centroids
cluster_centroids <- post_thread_text_sample %>% 
  group_by(k2) %>% 
  summarize( x.mean = mean(x),
             y.mean = mean(y))

# Compute WSS for this K value.
WSS_k2 <- post_thread_text_sample %>% 
  left_join(cluster_centroids, by = "k2") %>% 
  select(post_thread_id, k2, 
         x, y,
         x.mean, y.mean) %>% 
  mutate(dist.centr = sqrt((x - x.mean)^2 + (y - y.mean)^2)) %>% 
  group_by(k2) %>% 
  summarize(WSS = sum(dist.centr)) %>% 
  summarise(TWSS = sum(WSS)) %>% 
  pull()


#K3
# Compute Centroids
cluster_centroids <- post_thread_text_sample %>% 
  group_by(k3) %>% 
  summarize( x.mean = mean(x),
             y.mean = mean(y))

# Compute WSS for this K value.
WSS_k3 <- post_thread_text_sample %>% 
  left_join(cluster_centroids, by = "k3") %>% 
  select(post_thread_id, k3, 
         x, y,
         x.mean, y.mean) %>% 
  mutate(dist.centr = sqrt((x - x.mean)^2 + (y - y.mean)^2)) %>% 
  group_by(k3) %>% 
  summarize(WSS = sum(dist.centr)) %>% 
  summarise(TWSS = sum(WSS)) %>% 
  pull()

#K4
# Compute Centroids
cluster_centroids <- post_thread_text_sample %>% 
  group_by(k4) %>% 
  summarize( x.mean = mean(x),
             y.mean = mean(y))

# Compute WSS for this K value.
WSS_k4 <- post_thread_text_sample %>% 
  left_join(cluster_centroids, by = "k4") %>% 
  select(post_thread_id, k4, 
         x, y,
         x.mean, y.mean) %>% 
  mutate(dist.centr = sqrt((x - x.mean)^2 + (y - y.mean)^2)) %>% 
  group_by(k4) %>% 
  summarize(WSS = sum(dist.centr)) %>% 
  summarise(TWSS = sum(WSS)) %>% 
  pull()

#K5
# Compute Centroids
cluster_centroids <- post_thread_text_sample %>% 
  group_by(k5) %>% 
  summarize( x.mean = mean(x),
             y.mean = mean(y))

# Compute WSS for this K value.
WSS_k5 <- post_thread_text_sample %>% 
  left_join(cluster_centroids, by = "k5") %>% 
  select(post_thread_id, k5, 
         x, y,
         x.mean, y.mean) %>% 
  mutate(dist.centr = sqrt((x - x.mean)^2 + (y - y.mean)^2)) %>% 
  group_by(k5) %>% 
  summarize(WSS = sum(dist.centr)) %>% 
  summarise(TWSS = sum(WSS)) %>% 
  pull()

#K6
# Compute Centroids
cluster_centroids <- post_thread_text_sample %>% 
  group_by(k6) %>% 
  summarize( x.mean = mean(x),
             y.mean = mean(y))

# Compute WSS for this K value.
WSS_k6 <- post_thread_text_sample %>% 
  left_join(cluster_centroids, by = "k6") %>% 
  select(post_thread_id, k6, 
         x, y,
         x.mean, y.mean) %>% 
  mutate(dist.centr = sqrt((x - x.mean)^2 + (y - y.mean)^2)) %>% 
  group_by(k6) %>% 
  summarize(WSS = sum(dist.centr)) %>% 
  summarise(TWSS = sum(WSS)) %>% 
  pull()
    
#K7
# Compute Centroids
cluster_centroids <- post_thread_text_sample %>% 
  group_by(k7) %>% 
  summarize( x.mean = mean(x),
             y.mean = mean(y))

# Compute WSS for this K value.
WSS_k7 <- post_thread_text_sample %>% 
  left_join(cluster_centroids, by = "k7") %>% 
  select(post_thread_id, k7, 
         x, y,
         x.mean, y.mean) %>% 
  mutate(dist.centr = sqrt((x - x.mean)^2 + (y - y.mean)^2)) %>% 
  group_by(k7) %>% 
  summarize(WSS = sum(dist.centr)) %>% 
  summarise(TWSS = sum(WSS)) %>% 
  pull()
    
reddit_WSS <- data.frame(clusters = c(2:7),
           WSS = c(WSS_k2,WSS_k3,WSS_k4,WSS_k5,WSS_k6,WSS_k7)) %>% 
  ggplot(aes(x = clusters,
             y = WSS))+
  geom_line(color = my_palette[1])+
  geom_point(size = 2, color = my_palette[1]) +
  labs(title = "Reddit Threads Clustering Variation",
       subtitle = "Within Sum of Squares for Hierarchical Clustering",
       x = "Number of Clusters (k clusters)",
       y = "Within Sum of Squares")+
  theme_light()+
  theme(aspect.ratio = 1/1.618,
        plot.title = element_text(size = 18),
        axis.line = element_line(color = "black"),
        axis.ticks = element_line(color = "black"),
        panel.grid = element_line(color = "grey", linetype = 1,size = 0.25))

ggsave(filename = here::here("Thesis_Tex/Content/Images/reddit_wss.png"), reddit_WSS)
```

```{r}
fviz_dend(dendro_pca, k = 3, cex = 0.5,  show_labels = F, k_colors = my_palette) +
  labs(x = "Document ID",
       y = "Height",
       title = "reddit Thread Documents - HClust",
       subtitle = "Manhattan Distance & Ward.D Linkage")

fviz_dend(dendro_pca, k = 4, cex = 0.5,  show_labels = F, k_colors = my_palette) +
  labs(x = "Document ID",
       y = "Height",
       title = "reddit Thread Documents - HClust",
       subtitle = "Manhattan Distance & Ward.D Linkage")

```


```{r}
colnames(post_thread_text_sample)

post_thread_text_sample$queryword %>% unique() %>% sort()

querywords_df <- data.frame(id = 1:18,
                            word = c("anxious", "anxiety", 
                   "depressed", "depression",
                   "mental", "illness", "scared",
                   "afraid", "sad", "emotion", "anger",
                   "angry", "upset", "suicide", "abuse",
                   "emotional","help", "addiction"))
post_thread_text_sample <- left_join(post_thread_text_sample, querywords_df, by = c("queryword" = "id"))

post_thread_text_sample %>% 
  select(post_thread_id, word, k3, k5, k7)
```

```{r}
query_words_denominators <- post_thread_text_sample %>% 
  select(word) %>% 
  group_by(word) %>% 
  count()

cluster_denoms_k2 <- post_thread_text_sample %>% 
  select(k2) %>% 
  group_by(k2) %>% 
  count()
cluster_denoms_k3 <- post_thread_text_sample %>% 
  select(k3) %>% 
  group_by(k3) %>% 
  count()
cluster_denoms_k4 <- post_thread_text_sample %>% 
  select(k4) %>% 
  group_by(k4) %>% 
  count()
cluster_denoms_k5 <- post_thread_text_sample %>% 
  select(k5) %>% 
  group_by(k5) %>% 
  count()
cluster_denoms_k6 <- post_thread_text_sample %>% 
  select(k6) %>% 
  group_by(k6) %>% 
  count()
cluster_denoms_k7 <- post_thread_text_sample %>% 
  select(k7) %>% 
  group_by(k7) %>% 
  count()

# K2
pk2 <- post_thread_text_sample %>% 
  select(word, k2) %>%
  group_by(word, k2) %>% 
  count() %>% 
  left_join(cluster_denoms_k2, by = "k2") %>% 
  mutate(prop=n.x/n.y) %>% 
  ggplot(aes(x = as.factor(word),
             y = as.factor(k2), 
             fill = prop))+
    geom_tile(color = "black", size = 0.1)+
  scale_fill_gradient(low= my_palette[3] , high = my_palette[1])+
  #coord_flip()+
  theme_light()+
  theme(aspect.ratio = 1/1.618,
        plot.title = element_text(size = 12),
        axis.line = element_line(color = "black"),
        legend.position = "bottom",
        axis.ticks = element_line(color = "black"),
        axis.text.x = element_text(angle = 45, vjust = 0.15),
        panel.grid = element_line(color = "grey", linetype = 1,size = 0.25)) +
  labs(x = "", y = "Cluster",
       fill = "Proportion",
       title = "Cluster Membership: 2 clusters")

# K3
pk3 <- post_thread_text_sample %>% 
  select(word, k3) %>%
  group_by(word, k3) %>% 
  count() %>% 
  left_join(cluster_denoms_k3, by = "k3") %>% 
  mutate(prop=n.x/n.y) %>% 
  ggplot(aes(x = as.factor(word),
             y = as.factor(k3), 
             fill = prop))+
    geom_tile(color = "black", size = 0.1)+
  scale_fill_gradient(low= my_palette[3] , high = my_palette[1])+
  #coord_flip()+
  theme_light()+
  theme(aspect.ratio = 1/1.618,
        plot.title = element_text(size = 12),
        axis.line = element_line(color = "black"),
        legend.position = "bottom",
        axis.ticks = element_line(color = "black"),
        axis.text.x = element_text(angle = 45, vjust = 0.15),
        panel.grid = element_line(color = "grey", linetype = 1,size = 0.25)) +
  labs(x = "", y = "Cluster",
       fill = "Proportion",
       title = "Cluster Membership: 3 clusters")

# K3
pk4 <- post_thread_text_sample %>% 
  select(word, k4) %>%
  group_by(word, k4) %>% 
  count() %>% 
  left_join(cluster_denoms_k4, by = "k4") %>% 
  mutate(prop=n.x/n.y) %>% 
  ggplot(aes(x = as.factor(word),
             y = as.factor(k4), 
             fill = prop))+
    geom_tile(color = "black", size = 0.1)+
  scale_fill_gradient(low= my_palette[3] , high = my_palette[1])+
  #coord_flip()+
  theme_light()+
  theme(aspect.ratio = 1/1.618,
        plot.title = element_text(size = 12),
        axis.line = element_line(color = "black"),
        legend.position = "bottom",
        axis.ticks = element_line(color = "black"),
        axis.text.x = element_text(angle = 45, vjust = 0.15),
        panel.grid = element_line(color = "grey", linetype = 1,size = 0.25)) +
  labs(x = "", y = "Cluster",
       fill = "Proportion",
       title = "Cluster Membership: 4 clusters")

# K5
pk5 <- post_thread_text_sample %>% 
  select(word, k5) %>%
  group_by(word, k5) %>% 
  count() %>% 
  left_join(cluster_denoms_k5, by = "k5") %>% 
  mutate(prop=n.x/n.y) %>% 
  ggplot(aes(x = as.factor(word),
             y = as.factor(k5), 
             fill = prop))+
    geom_tile(color = "black", size = 0.1)+
  scale_fill_gradient(low= my_palette[3] , high = my_palette[1])+
  #coord_flip()+
  theme_light()+
  theme(aspect.ratio = 1/1.618,
        plot.title = element_text(size = 12),
        axis.line = element_line(color = "black"),
        legend.position = "bottom",
        axis.ticks = element_line(color = "black"),
        axis.text.x = element_text(angle = 45, vjust = 0.15),
        panel.grid = element_line(color = "grey", linetype = 1,size = 0.25)) +
  labs(x = "", y = "Cluster",
       fill = "Proportion",
       title = "Cluster Membership: 5 clusters")

# K6
pk6 <- post_thread_text_sample %>% 
  select(word, k6) %>%
  group_by(word, k6) %>% 
  count() %>% 
  left_join(cluster_denoms_k6, by = "k6") %>% 
  mutate(prop=n.x/n.y) %>% 
  ggplot(aes(x = as.factor(word),
             y = as.factor(k6), 
             fill = prop))+
    geom_tile(color = "black", size = 0.1)+
  scale_fill_gradient(low= my_palette[3] , high = my_palette[1])+
  #coord_flip()+
  theme_light()+
  theme(aspect.ratio = 1/1.618,
        plot.title = element_text(size = 12),
        axis.line = element_line(color = "black"),
        legend.position = "bottom",
        axis.ticks = element_line(color = "black"),
        axis.text.x = element_text(angle = 45, vjust = 0.15),
        panel.grid = element_line(color = "grey", linetype = 1,size = 0.25)) +
  labs(x = "", y = "Cluster",
       fill = "Proportion",
       title = "Cluster Membership: 6 clusters")

# K7
pk7 <- post_thread_text_sample %>% 
  select(word, k7) %>%
  group_by(word, k7) %>% 
  count() %>% 
  left_join(cluster_denoms_k7, by = "k7") %>% 
  mutate(prop=n.x/n.y) %>% 
  ggplot(aes(x = as.factor(word),
             y = as.factor(k7), 
             fill = prop))+
    geom_tile(color = "black", size = 0.1)+
  scale_fill_gradient(low= my_palette[3] , high = my_palette[1])+
  #coord_flip()+
  theme_light()+
  theme(aspect.ratio = 1/1.618,
        plot.title = element_text(size = 12),
        axis.line = element_line(color = "black"),
        legend.position = "bottom",
        axis.ticks = element_line(color = "black"),
        axis.text.x = element_text(angle = 45, vjust = 0.15),
        panel.grid = element_line(color = "grey", linetype = 1,size = 0.25)) +
  labs(x = "", y = "Cluster",
       fill = "Proportion",
       title = "Cluster Membership: 7 clusters")


## Dendrograms 
dend2 <- fviz_dend(dendro_pca, k = 2, cex = 0.5,  show_labels = F, k_colors = my_palette) +
  labs(x = "Document ID",
       y = "Height",
       title = "reddit Thread Documents - HClust",
       subtitle = "Manhattan Distance & Ward.D Linkage")
dend3 <- fviz_dend(dendro_pca, k = 3, cex = 0.5,  show_labels = F, k_colors = my_palette) +
  labs(x = "Document ID",
       y = "Height",
       title = "reddit Thread Documents - HClust",
       subtitle = "Manhattan Distance & Ward.D Linkage")
dend4 <- fviz_dend(dendro_pca, k = 4, cex = 0.5,  show_labels = F, k_colors = my_palette) +
  labs(x = "Document ID",
       y = "Height",
       title = "reddit Thread Documents - HClust",
       subtitle = "Manhattan Distance & Ward.D Linkage")
dend5 <- fviz_dend(dendro_pca, k = 5, cex = 0.5,  show_labels = F, k_colors = my_palette) +
  labs(x = "Document ID",
       y = "Height",
       title = "reddit Thread Documents - HClust",
       subtitle = "Manhattan Distance & Ward.D Linkage")
dend6 <- fviz_dend(dendro_pca, k = 6, cex = 0.5,  show_labels = F, k_colors = my_palette) +
  labs(x = "Document ID",
       y = "Height",
       title = "reddit Thread Documents - HClust",
       subtitle = "Manhattan Distance & Ward.D Linkage")
dend7 <- fviz_dend(dendro_pca, k = 7, cex = 0.5,  show_labels = F, k_colors = my_palette) +
  labs(x = "Document ID",
       y = "Height",
       title = "reddit Thread Documents - HClust",
       subtitle = "Manhattan Distance & Ward.D Linkage")

```

```{r}
library(patchwork)

pk2dend <- pk2+dend2
pk3dend <- pk3+dend3
pk4dend <- pk4+dend4
pk5dend <- pk5+dend5
pk6dend <- pk6+dend6
pk7dend <- pk7+dend7

ggsave(here::here("Thesis_Tex/Content/Images/k2_reddit_clusters.png"), pk2dend)
ggsave(here::here("Thesis_Tex/Content/Images/k3_reddit_clusters.png"), pk3dend)
ggsave(here::here("Thesis_Tex/Content/Images/k4_reddit_clusters.png"), pk4dend)
ggsave(here::here("Thesis_Tex/Content/Images/k5_reddit_clusters.png"), pk5dend)
ggsave(here::here("Thesis_Tex/Content/Images/k6_reddit_clusters.png"), pk6dend)
ggsave(here::here("Thesis_Tex/Content/Images/k7_reddit_clusters.png"), pk7dend)
```

# Kernel Density Estimate Clustering

```{r, include=F, eval=FALSE}
#clean up work space.
rm(cluster_centroids,cluster_denoms_k2,cluster_denoms_k3,cluster_denoms_k4,cluster_denoms_k5,cluster_denoms_k6,cluster_denoms_k7,dend2,dend3,dend4,dend5,dend6,dend7, k3_counts, k3_cluster_counts,k3_tf_idf,scaled_kernel)
```


```{r}
set.seed(23)
random_thread <- sample(1:150, 1)
study_post <- post_thread_text_sample[random_thread,]
study_kernel <- reddit_thread_kernel_matrix[random_thread,]

study_kernel %>% as.data.frame() %>% 
  drop_na() %>% 
  ggplot(aes(x = `.`))+
  geom_density(bw=0.001) +
  theme(plot.background = element_rect(fill = "white", colour = NA),
        panel.background = element_rect(fill = "white", colour = NA),
        axis.line = element_line(colour = "black"),
        panel.grid.major.x = element_line(color = "gray80", size = 0.5),
        panel.grid.major.y = element_line(color = "gray80", size = 0.5),
        title =element_text(size=12, face='bold'))

# Compute First and Second Derivs.
data.frame(x = density(study_kernel, bw = 0.001, na.rm = T)$x,
           y = density(study_kernel, bw = 0.001, na.rm = T)$y) %>% 
  mutate(x_l = lag(x),
         y_l = lag(y)) %>% 
  mutate(y_prime = (y - y_l)/(x - x_l)) %>% 
  mutate(y_prime_l = lag(y_prime)) %>% 
  mutate(y_prpr = (y_prime - y_prime_l)/(x - x_l)) %>% 
  ggplot(aes(x, y_prpr))+
  geom_line()+
  geom_point()+
  labs(title = "f''(x)")+
  theme(plot.background = element_rect(fill = "white", colour = NA),
        panel.background = element_rect(fill = "white", colour = NA),
        axis.line = element_line(colour = "black"),
        panel.grid.major.x = element_line(color = "gray80", size = 0.5),
        panel.grid.major.y = element_line(color = "gray80", size = 0.5),
        title =element_text(size=12, face='bold'))

# Find Zeros
data.frame(x = density(study_kernel, bw = 0.001, na.rm = T)$x,
           y = density(study_kernel, bw = 0.001, na.rm = T)$y) %>% 
  mutate(x_l = lag(x),
         y_l = lag(y)) %>% 
  mutate(y_prime = (y - y_l)/(x - x_l)) %>% 
  mutate(y_prime_l = lag(y_prime)) %>% 
  mutate(y_prpr = (y_prime - y_prime_l)/(x - x_l)) %>% 
  mutate(is_zero = ifelse(
    sign(y_prpr) != sign(lag(y_prpr)) 
    |
    sign(y_prpr) != sign(lead(y_prpr))
    , T,F
    )) %>% 
  ggplot(aes(x, y_prpr))+
  geom_line()+
  geom_point(aes(color = is_zero))+
  labs(title = "f''(x)")+
  theme(plot.background = element_rect(fill = "white", colour = NA),
        panel.background = element_rect(fill = "white", colour = NA),
        axis.line = element_line(colour = "black"),
        panel.grid.major.x = element_line(color = "gray80", size = 0.5),
        panel.grid.major.y = element_line(color = "gray80", size = 0.5),
        title =element_text(size=12, face='bold'))

# 
ex_df <- data.frame(x = density(study_kernel, bw = 0.001, na.rm = T, n = 1024)$x,
           y = density(study_kernel, bw = 0.001, na.rm = T, n = 1024)$y) %>% 
  mutate(x_l = lag(x),
         y_l = lag(y)) %>% 
  mutate(y_prime = (y - y_l)/(x - x_l)) %>% 
  mutate(y_prime_l = lag(y_prime)) %>% 
  mutate(y_prpr = (y_prime - y_prime_l)/(x - x_l)) %>% 
  mutate(is_zero = ifelse(
    sign(y_prpr) != sign(lag(y_prpr)) 
    |
      sign(y_prpr) != sign(lead(y_prpr))
    , T,F
  )) 

# Get cluster breaks.
ex_cluster_breaks <- ex_df %>% 
  filter(is_zero == TRUE) %>% 
  select(x) %>% 
  pull()

mean_break_pts <- function(est_breaks_pts){
  # allocate space.
  mean_pts <- rep(0, length(est_breaks_pts)-1)
  
  # loop through pairs.
  for(i in 1:(length(est_breaks_pts)-1)){
    mean_tmp <- mean(c(est_breaks_pts[i], est_breaks_pts[i+1]))
    mean_pts[i] <- mean_tmp
  }
  return(mean_pts)
}

ex_cluster_breaks <- mean_break_pts(ex_cluster_breaks)


# Assign labels
label_cluster <- function(values, breaks){
  number_of_breaks <- length(breaks)
  
  # Allocate Space.
  cluster_cols <- data.frame(x = values)
  cluster_labels <- rep(0,length(values))
  # Check if value is in break bounds.
  for(i in 1:number_of_breaks){
    bool_in_cluster <- (values > breaks[i] & values < breaks[i+1]) 
    #cluster_labels <- ifelse(bool_in_cluster, i, NA)
    cluster_labels <- bool_in_cluster
    # Add new cluster label column
    cluster_cols <- cbind(cluster_cols, cluster_labels)
    # Name each column.
    colnames(cluster_cols) <- c(colnames(cluster_cols[1:length(cluster_cols)-1]),i)
  }
  return(cluster_cols)
}

label_cluster(ex_df$x, ex_cluster_breaks) 
ex_df2 <- cbind(1:nrow(ex_df), ex_df, label_cluster(ex_df$x, ex_cluster_breaks))
colnames(ex_df2) <- c("id", colnames(ex_df2[,2:ncol(ex_df2)]))

ex_df_labels <- ex_df2[c(1,10:37)] %>% 
  pivot_longer(cols = c("1":"27")) %>% 
  filter(value == TRUE)

ex_df <- left_join(ex_df2, ex_df_labels, by = c())  

ex_df %>% 
  #filter(!is.na(name)) %>% 
  ggplot(aes(x = x, y = y, color = name)) +
  geom_point()
  
ex_df_summary <- ex_df %>% 
  group_by(name) %>% 
  summarize(group_sd = sd(x),
            group_mean = mean(x),
            group_med = median(x))

```
